apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-small
  namespace: elastic-system
spec:
  version: 8.13.0
  http:
    tls:
      selfSignedCertificate: { disabled: false }
  nodeSets:
  - name: all-in-one
    count: 2
    config:
      node.roles: ["master","data_hot","ingest","data_content"]
      xpack.ml.enabled: false
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
          resources:
            requests: { cpu: "500m", memory: "2Gi" }
            limits:   { cpu: "1",    memory: "2Gi" }
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2        # <<â€” IMPORTANT
        resources:
          requests:
            storage: 20Gi
