apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.13.0
  count: 1
  elasticsearchRef:
    name: es-small
  http:
    service:
      spec:
        type: LoadBalancer              # <--- this line makes it public
    tls:
      selfSignedCertificate:
        disabled: false                 # enable HTTPS with self-signed cert
